USE [master]
GO

/****** Object:  Database [Modelos]    Script Date: 20-07-2022 23:22:56 ******/
CREATE DATABASE [Modelos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Modelos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Modelos.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Modelos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Modelos_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Modelos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Modelos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Modelos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Modelos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Modelos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Modelos] SET ARITHABORT OFF 
GO

ALTER DATABASE [Modelos] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Modelos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Modelos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Modelos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Modelos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Modelos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Modelos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Modelos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Modelos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Modelos] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Modelos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Modelos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Modelos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Modelos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Modelos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Modelos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Modelos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Modelos] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Modelos] SET  MULTI_USER 
GO

ALTER DATABASE [Modelos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Modelos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Modelos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Modelos] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Modelos] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Modelos] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Modelos] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Modelos] SET  READ_WRITE 
GO


CREATE TABLE [dbo].[Lecturas](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdMedidor] [int] NOT NULL,
	[Consumo] [varchar](10) NOT NULL,
	[Fecha] [smalldatetime] NOT NULL
) ON [PRIMARY]
GO

USE [MedidoresDB]
GO

/****** Object:  Table [dbo].[Medidor]    Script Date: 20-07-2022 13:40:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Medidor](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdMedidor] [int] NULL,
	[Tipo] [varchar](10) NULL
) ON [PRIMARY]
GO


